### ISSUE TITLE
Type B Uncertainty's

### ISSUE THREAD

**Issue by davidgreavesau** [icsm-au/datum-modernisation#4]
Hi,

I was wondering is there an underlying document that helps explain where the Type B Uncertainty values in the python script come from?

We have been using (3, 1, 6) for horizontal that were in the GNSS CORS Position Verification Analysis Report and I was interested in seeing if a similar document existed that explains the two sets of values in the script.

Ta.

**Comment by nicgowans** [comment]
G'day, David. 

I'll leave it for some one at GA to comment on any documentation, but keep in mind the numbers in that report are expressed at the 95% CL. When expressed at one-sigma, and added together in quadrature, you end up with values of ~3.5 mm and ~7 mm in horizontal and vertical components, respectively.

In that sense, the script applies comparable values to the report for RVS stations, but in East, North and Up (3, 3, 6 mm at one-sigma). The second set of values (6, 6, 12) which is applied to all other stations acknowledges that the instrumentation, monument quality, etc., perhaps isn't quite as refined as the RVS stations.

Nic

**Comment by davidgreavesau** [comment]
Thanks that has clears up the RVS values for me. I had read them slightly differently but as you say they are comparable.
Dave.

**Comment by harry093** [comment]
@davidgreavesau, sorry for missing this.

Yes, what @nicgowans has said is correct. The RVS Type B uncertainties are slightly smaller due to the fact that the RVS positions were determined from a time series combination. That is, all available data for each station was used to determine the most accurate position possible.

Reg 13 certificates, on the other hand, give positions determined from only one week of data.

A paper is being written covering all this and I expect it to be ready soon.

**Comment by davidgreavesau** [comment]
Thanks for the update @harry093 .

Looking forward to seeing the paper once it is  published to see how the other numbers relate. We have been working on 6.8mm as our Type B when trying to generate an estimated positional uncertainty.
